name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker buildx build \
            --build-arg VITE_API_BLIKON_AUTH=${{ vars.VITE_API_BLIKON_AUTH }} \
            --build-arg VITE_BLIKON_AUTH_TOKEN=${{ secrets.VITE_BLIKON_AUTH_TOKEN }} \
            --build-arg VITE_ENVIRONMENT=development \
            --tag ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/front-comunicacion-dev:${{ github.sha }} \
            --tag ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/front-comunicacion-dev:latest \
            --push .
